In [8]:
import tensorflow as tf
import numpy as np 

2022-12-03 00:12:32.073228: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0


In [9]:
data_x = np.load("numpy_data/ei-testing-lstm-raw-data-X.npy")
data_y = np.load("numpy_data/ei-testing-lstm-raw-data-y.npy")

In [41]:
data_x.shape

(16, 7263)

In [42]:
data_y.shape

(16, 4)

In [43]:
data_x[2].shape

(7263,)

In [44]:
data_y[0].shape

(4,)

In [45]:
len(data_x[2].tolist())

7263

In [46]:
data_x[0]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [47]:
data_x[1]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [48]:
data_x[2]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [49]:
data_x[3]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [50]:
data_y[1]

array([        1, 154091060,         0,      2421], dtype=int32)

In [51]:
data_y[2]

array([        1, 154091059,         0,      2421], dtype=int32)

In [52]:
data_y[3]

array([        1, 154091057,         0,      2421], dtype=int32)

In [53]:
data_y[4]

array([        1, 154091054,         0,      2421], dtype=int32)

In [54]:
data_y[5]

array([        1, 154091053,         0,      2421], dtype=int32)

In [55]:
data_y[15]

array([        2, 154091040,         0,      2421], dtype=int32)

In [61]:
len(data_y[15].tolist())

4

In [58]:
# data_y[20]

In [59]:
# data_y[23]

In [39]:
data_x = np.load("data_raw/x.npy")
data_y = np.load("data_raw/y.npy")